version: "2"

services:
  shell:
    #this will be my custom image since i have some other stuff to add
    image: hyperledger/sawtooth-shell
    container_name: sawtooth-shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  #
  validator-0:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-default-0
    hostname: validator-0
    ports:
      - "4004"
      - "8800"
    command: "bash -c \"\
        sawadm keygen --force && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm=poet \
          sawtooth.poet.report_public_key_pem=\
          \\\"$$(cat /etc/sawtooth/simulator_rk_pub.pem)\\\" \
          sawtooth.poet.valid_enclave_measurements=$$(poet enclave measurement) \
          sawtooth.poet.valid_enclave_basenames=$$(poet enclave basename) \
          -o config.batch && \
        poet registration create -k /etc/sawtooth/keys/validator.priv -o poet.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
             sawtooth.poet.target_wait_time=1 \
             sawtooth.poet.initial_wait_time=25 \
             sawtooth.poet.ztest_minimum_win_count=999999999 \
             sawtooth.publisher.max_batches_per_block=100 \
          -o poet-settings.batch && \
        sawadm genesis \
          config-genesis.batch config.batch poet.batch poet-settings.batch && \
        sawtooth-validator -v \
          --bind network:tcp://eth0:8800 \
          --bind component:tcp://eth0:4004 \
          --peering dynamic \
          --endpoint tcp://validator-0:8800 \
          --scheduler parallel \
          --network trust
    \""
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL

  rest-api-0:
    image: hyperledger/sawtooth-rest-api
    container_name: rest-api-default-0
    ports:
      - "8008:8008"
      - "4004"
    command: sawtooth-rest-api -v -C tcp://validator-0:4004 --bind rest-api-0:8008
    stop_signal: SIGKILL
  
  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp-default-0
    ports:
      - "4004"
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL

  
  
  poet-validator-registry-tp-0:
    image: hyperledger/sawtooth-poet-validator-registry-tp
    container_name: sawtooth-poet-validator-registry-tp-0
    ports:
      - "4004"
    command: poet-validator-registry-tp -C tcp://validator-0:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

  sawtooth-tp-0:
    image: isaacprasanth/supplychain-custom-saw
    container_name: sawtooth-tp-default-0
    ports:
      - "4004"
    command: bash -c \ 
             "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/sawtooth/proc/main.py tcp://validator-0:4004 "
              
    stop_signal: SIGKILL
  
  sawtooth-tp-0-1:
    image: isaacprasanth/supplychain-custom-saw
    container_name: sawtooth-tp-default-0-1
    ports:
      - "4004"
    command: bash -c \ 
             "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/sawtooth/proc/main.py tcp://validator-0:4004 "
              
    stop_signal: SIGKILL
  
  sawtooth-tp-0-2:
    image: isaacprasanth/supplychain-custom-saw
    container_name: sawtooth-tp-default-0-2
    ports:
      - "4004"
    command: bash -c \ 
             "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/sawtooth/proc/main.py tcp://validator-0:4004 "
              
    stop_signal: SIGKILL


  #wallet tp
  wallet-tp-0:
    image: isaacprasanth/supplychain-custom-saw
    container_name: wallet-tp-default-0
    ports:
      - "4004"
    command: bash -c \ 
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/wallet_tf/proc/main.py tcp://validator-0:4004 "
              
  validator-1:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-default-1
    hostname: validator-1
    ports:
      - "4004"
      - "8800"
    command: |
      bash -c "
        sawadm keygen --force && \
        sawtooth-validator -v --bind network:tcp://eth0:8800 --bind component:tcp://eth0:4004 --peering dynamic --endpoint tcp://validator-1:8800 --seeds tcp://validator-0:8800 --scheduler parallel --network trust"
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL


  rest-api-1:
    image: hyperledger/sawtooth-rest-api
    container_name: rest-api-default-1
    hostname: rest-api-1
    ports:
      - "8008"
      - "4004"
      
    command: bash -c "sawtooth-rest-api -C tcp://validator-1:4004 --bind rest-api-1:8008"
    stop_signal: SIGKILL

  
  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp-default-1
    ports:
      - "4004"
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-1:
    image: hyperledger/sawtooth-poet-validator-registry-tp
    container_name: sawtooth-poet-validator-registry-tp-1
    ports:
      - "4004"
    command: poet-validator-registry-tp -C tcp://validator-1:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL


  sawtooth-tp-1:
    image: isaacprasanth/supplychain-custom-saw
    container_name: sawtooth-tp-default-1
    ports:
      - "4004"
    command: bash -c \ 
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/sawtooth/proc/main.py tcp://validator-1:4004 "
              
    stop_signal: SIGKILL

  wallet-tp-1:
    image: isaacprasanth/supplychain-custom-saw
    container_name: wallet-tp-default-1
    ports:
      - "4004"
    command: bash -c \ 
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/wallet_tf/proc/main.py tcp://validator-1:4004 "
              
    stop_signal: SIGKILL

  djano-server-1:
    image: isaacprasanth/supplychain-django
    container_name: django-server-default-1
    ports:
      - "8000:8000"
      - "8008"
    labels:
      kompose.service.expose: "django-server-1"
    command: bash -c \
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git && sawtooth keygen ubuntu &&  python3 webapp/profiles/wallet/settingup-website.py && python3 supplychain/webapp/manage.py runserver 0:8000 "



  validator-2:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-default-2
    ports:
      - "4004"
      - "8800"
    hostname: validator-2
    command: |
      bash -c "
        sawadm keygen --force && \
        sawtooth-validator -v --bind network:tcp://eth0:8800 --bind component:tcp://eth0:4004 --peering dynamic --endpoint tcp://validator-2:8800 --seeds tcp://validator-0:8800 --scheduler parallel --network trust"
    environment:
      PYTHONPATH: "/project/sawtooth-core/consensus/poet/common:\
        /project/sawtooth-core/consensus/poet/simulator:\
        /project/sawtooth-core/consensus/poet/core"
    stop_signal: SIGKILL


  rest-api-2:
    image: hyperledger/sawtooth-rest-api
    container_name: rest-api-default-2
    ports:
      - "8008"     
      - "4004"
    command: bash -c "sawtooth-rest-api -C tcp://validator-2:4004 --bind http://rest-api-2:8008"
    stop_signal: SIGKILL

  
  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp-default-2
    ports:
      - "4004"
    command: settings-tp -C tcp://validator-2:4004
    stop_signal: SIGKILL

  poet-validator-registry-tp-2:
    image: hyperledger/sawtooth-poet-validator-registry-tp
    container_name: sawtooth-poet-validator-registry-tp-2
    ports:
      - "4004"
    command: poet-validator-registry-tp -C tcp://validator-2:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL


  sawtooth-tp-2:
    image: isaacprasanth/supplychain-custom-saw
    container_name: sawtooth-tp-default-2
    ports:
      - "4004"
    command: bash -c \ 
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/sawtooth/proc/main.py tcp://validator-2:4004 "
              
    stop_signal: SIGKILL

  wallet-tp-2:
    image: isaacprasanth/supplychain-custom-saw
    container_name: wallet-tp-default-2
    ports:
      - "4004"
    command: bash -c \ 
              "git clone -b webapp-beta https://github.com/GuyFawkes1/supplychain.git  && /usr/bin/python3 supplychain/Transaction_Families/wallet_tf/proc/main.py tcp://validator-2:4004 "
              
    stop_signal: SIGKILL